resolver: lts-12.26

extra-packages:
    - githash-0.1.3.0
    - hspec-expectations-lifted-0.10.0
    - hspec-megaparsec-1.1.0
    - megaparsec-6.5.0
    - neat-interpolation-0.3.2.2
    - placeholders-0.1
    - rdtsc-1.3.0.1
    - mtl-c-0.1.1
    - weigh-0.0.13
    - path-io-1.4.2

ghc-options:
    $locals:
        -O1
        -Wall
        -Wno-name-shadowing
        -fexcess-precision
        -fexpose-all-unfoldings
        -flate-dmd-anal
        -fmax-worker-args=1000
        -fsimpl-tick-factor=400
        -fspec-constr-keen
        -fspecialise-aggressively
        -fstatic-argument-transformation
        -funbox-strict-fields
        -threaded
        -fomit-interface-pragmas
    $everything:
        -fconstraint-solver-iterations=100

packages:
    - core
    - debug
    - passes
    - package
    - path
    - runtime
    - stdlib
    - shell
    - syntax/text/lexer
    - syntax/text/model
    - syntax/text/parser
    - syntax/text/builder
    - syntax/text/prettyprint

    - lib/autovector
    - lib/ci
    - lib/code-builder
    - lib/container
    - lib/convert
    - lib/cpp-containers
    - lib/data-construction
    - lib/data-poset
    - lib/data-property
    - lib/data-storable
    - lib/data-tag
    - lib/data-typemap
    - lib/datafile
    - lib/exception
    - lib/foreign-utils
    - lib/functor-utils
    - lib/future
    - lib/generic-traversable
    - lib/generic-traversable2
    - lib/hspec-jenkins
    - lib/impossible
    - lib/layered-state
    - lib/layouting
    - lib/lens-utils
    - lib/memory-manager
    - lib/memory-pool
    - lib/monad-branch
    - lib/monoid
    - lib/nested-containers
    - lib/parser-utils
    - lib/prologue
    - lib/syntax-definition
    - lib/terminal-text
    - lib/text-processing
    - lib/th-builder
    - lib/tuple-utils
    - lib/type-cache
    - lib/typelevel
    - lib/vector-text
    - lib/yaml-utils
